import Layout from '../components/layout'
import Head from "next/head";
import {projectsView} from "../components/projects/projectsView";


function projects() {
    return (
        <Layout>
            <Head>
                <title>Projects</title>
                <meta name="Projects by Austin Nazworth" content="Generated by create next app"/>
                <link rel="icon" href="/curryfavicon.ico"/>
            </Head>
            {projectsView(PROJECTS)}
        </Layout>
   )
}
export default projects;

const PROJECTS: object = [
    { id: 1,
        title: 'This Site',
        description: 'My personal website, you know, the one you\'re looking at.',
        image: '/anazworthHomepage.png',
        alt: 'Austin Nazworth\'s Homepage',
        link: 'https://www.anazworth.com/',
        stack: ['Next.js', 'TailWind CSS', 'DaisyUI', 'TypeScript'],
    },
    { id: 2,
        title: 'North Florida Communications',
        description: 'A website for a commercial phone and networking company.',
        image: '/nfcHomepage.png',
        alt: 'North Florida Communications',
        link: 'https://www.northfloridacommunications.com/',
        stack: ['Next.js', 'TailWind CSS', 'Chakra UI', 'email.js', 'TypeScript'],
    },
    {
        id: 3,
        title: 'Sleep Statistics',
        description: 'A school project taken too far.',
        image: '/sleepData.png',
        alt: 'Sleep Data Project',
        link: 'https://anazworth.com/sleep/data',
        altLink: 'https://www.github.com/anazworth/sleepStats',
        stack: ['Frontend: Next.js, TailWind Css, TypeScript', 'Backend: Go, Gin, Gorm', 'Database: Postgres', 'Deployment: Docker, Ubuntu Server', 'Raspberry Pi 4'],
    }

];