import Layout from '../components/layout'
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";


function projects() {
    return (
        <Layout>
            <Head>
                <title>Projects</title>
                <meta name="Projects by Austin Nazworth" content="Generated by create next app" />
                <link rel="icon" href="/curryfavicon.ico" />
            </Head>
            <div className="flex flex-col min-h-screen">
                {PROJECTS.map((project, index) => (
                <div key={index} className="flex flex-col min-h-screen mx-auto p-4 justify-center content-center">
                    <div className="flex flex-col max-w-3xl mx-auto text-center justify-center">
                        <Link href={project.link}>
                            <a className="hover:text-nord14 hover:scale-105 duration-500">
                        <h1 className="flex text-4xl sm:text-6xl font-bold justify-center sm:whitespace-nowrap my-10">{project.title}</h1>
                            </a>
                        </Link>
                        <p className="flex text-lg text-center justify-center my-10">{project.description}</p>
                    </div>
                    <div className="flex flex-col justify-center bg-gradient-to-t from-nord2 to-nord0 space-y-8">
                        <div className="mt-4 sm:mt-4">
                        <h2 className="flex text-2xl font-bold underline justify-center">The Stack</h2>

                        <ul className="justify-center text-center ">
                            {project.stack.map((stack) => (
                                // eslint-disable-next-line react/jsx-key
                            <li className="flex text-lg text-center justify-center">{stack}</li>
                            ))}
                        </ul>
                        </div>
                        <div className="relative group mt-4 justify-center mx-auto">
                            <div className="absolute inset-0 blur bg-nord14
                                    group-hover:blur-xl transition duration-1000"></div>
                            <Image  src={project.image} alt={project.alt}
                                   layout={'intrinsic'} width={900} height={500} objectFit={'contain'}
                                    />
                        </div>
                    </div>
                </div>
                ))}
            </div>
        </Layout>
   )
}
export default projects;

const PROJECTS = [
    { id: 1,
        title: 'This Site',
        description: 'My personal website, you know, the one you\'re looking at.',
        image: '/anazworthHomepage.png',
        alt: 'Austin Nazworth\'s Homepage',
        link: 'https://www.anazworth.com/',
        stack: ['Next.js', 'TailWind CSS', 'Chakra UI', 'TypeScript'],
    },
    { id: 2,
        title: 'North Florida Communications',
        description: 'A website for a commercial phone and networking company.',
        image: '/nfcHomepage.png',
        alt: 'North Florida Communications',
        link: 'https://www.northfloridacommunications.com/',
        stack: ['Next.js', 'TailWind CSS', 'Chakra UI', 'email.js', 'TypeScript'],
    },

];